### ISSUE TITLE
change background colors settings request

### ISSUE THREAD

**Issue by enots** [akiko-pusu/redmine_issue_favicon#6]
will be nice to see this and no need for patching issue_favicon.js by hands. 
this is good if you have a lot redmine instances.

**Comment by enots** [comment]
![2017-10-28_18_40_55](https://user-images.githubusercontent.com/5549126/32135959-d622334c-bc0f-11e7-9a8d-2669ef527f17.png)

**Comment by akiko-pusu** [comment]
Hi,@enots 
Thanks for your feedback!
I think this is not so difficult to change color  per redmine instances :)

**Comment by akiko-pusu** [comment]
Hi, @enots 
I'm going to implement this feature if you still hope.
Each user can customize favicon's bgColor, textColor.

PR: #13

**Comment by akiko-pusu** [comment]
Hello, might be too late, I tried to implement your request. I'll merge it soon.
